---
- hosts: localhost
  become: true
  gather_facts: false
  tasks:

    - name: Copy /etc/portage/make.conf
      copy:
        src: ./etc/portage/make.conf
        dest: /etc/portage/make.conf
        owner: root
        group: root

    - name: Copy package.accept_keywords
      copy:
        src: "./etc/portage/package.accept_keywords"
        dest: "/etc/portage/package.accept_keywords"
        owner: root
        group: root

    # - name: Copy package.mask
    #   copy:
    #     src: "./etc/portage/package.mask/{{ item }}"
    #     dest: "/etc/portage/package.mask/{{ item }}"
    #     owner: root
    #     group: root
    #   loop:
    #     - emacs
    #     - mysql

    - name: Copy /etc/portage/package.unmask
      copy:
        src: ./etc/portage/package.unmask
        dest: /etc/portage/package.unmask
        owner: root
        group: root

    # - name: Copy package.use
    #   copy:
    #     src: "./etc/portage/package.use/{{ item }}"
    #     dest: "/etc/portage/package.use/{{ item }}"
    #     owner: root
    #     group: root
    #   loop:
    #     - emacs
    #     - emacs-common
    #     - git
    #     - qtwidgets
    #     - mysql
    #     - nodejs
    #     - onedrive
    #     - php
    #     - eselect-php
    #     - pinentry
    #     - systemd
    #     - libpcre2
    #     - lttng-ust
    #     - libcanberra
    #     - noto

    # - name: Copy /etc/portage/repos.conf/gentoo.conf
    #   copy:
    #     src: ./etc/portage/repos.conf/gentoo.conf
    #     dest: /etc/portage/repos.conf/gentoo.conf
    #     owner: root
    #     group: root

    - name: Copy /etc/wsl.conf
      copy:
        src: ./etc/wsl.conf
        dest: /etc/wsl.conf
        owner: root
        group: root

    - name: Install required packages
      portage:
        package: "{{ packages }}"
        state: present
      vars:
        packages:
          - app-admin/sudo
          - dev-vcs/git
          - app-editors/vim
          - app-admin/ansible
