---
- hosts: localhost
  become: true
  gather_facts: false
  tasks:

    - name: Copy /etc/portage/make.conf
      copy:
        src: ./etc/portage/make.conf
        dest: /etc/portage/make.conf
        owner: root
        group: root

    - name: Copy package.accept_keywords
      copy:
        src: "./etc/portage/package.accept_keywords"
        dest: "/etc/portage/package.accept_keywords"
        owner: root
        group: root

    # - name: Copy package.mask
    #   copy:
    #     src: "./etc/portage/package.mask/{{ item }}"
    #     dest: "/etc/portage/package.mask/{{ item }}"
    #     owner: root
    #     group: root
    #   loop:
    #     - emacs
    #     - mysql

    - name: Copy /etc/portage/package.unmask
      copy:
        src: ./etc/portage/package.unmask
        dest: /etc/portage/package.unmask
        owner: root
        group: root

    - name: Copy package.use
      copy:
        src: "./etc/portage/package.use/{{ item }}"
        dest: "/etc/portage/package.use/{{ item }}"
        owner: root
        group: root
      loop:
        - emacs
    #     - emacs-common
    #     - git
    #     - qtwidgets
    #     - mysql
        - nodejs
        - onedrive
        - php
    #     - eselect-php
    #     - pinentry
    #     - systemd
    #     - libpcre2
    #     - lttng-ust
    #     - libcanberra
    #     - noto
        - ffmpeg

    - name: Copy /etc/portage/package.license
      copy:
        src: ./etc/portage/package.license
        dest: /etc/portage/package.license
        owner: root
        group: root

    - name: Copy /etc/wsl.conf
      copy:
        src: ./etc/wsl.conf
        dest: /etc/wsl.conf
        owner: root
        group: root

    - name: Copy /etc/tmpfiles.d/wsl.conf
      copy:
        src: ./etc/tmpfiles.d/wsl.conf
        dest: /etc/tmpfiles.d/wsl.conf
        owner: root
        group: root

    ## see https://gist.github.com/onlime/8767e4e86d4205e32fbe354c8bea626c
    - name: Composer | Install Composer latest-stable
      get_url:
        url: https://getcomposer.org/download/latest-stable/composer.phar
        checksum: 'sha256:https://getcomposer.org/download/latest-stable/composer.phar.sha256sum'
        dest: /usr/local/bin/composer.phar
        mode: 0755

    - name: Composer | Symlink composer.phar
      file:
        src: composer.phar
        dest: /usr/local/bin/composer
        state: link

    - name: Install required packages
      portage:
        package: "{{ packages }}"
        state: present
      vars:
        packages:
          - app-admin/sudo
          - dev-vcs/git
          - app-editors/vim
          - app-admin/ansible
          - gui-apps/wl-clipboard
          - app-eselect/eselect-repository
          - app-editors/emacs
          - x11-apps/xrandr
          - x11-apps/xeyes
          - app-shells/zsh
          - media-fonts/udev-gothic
          - media-fonts/noto
          - app-text/cmigemo
          - dev-util/wakatime-cli
          - app-shells/fzf
          - x11-libs/libnotify
          - net-misc/onedrive
          - net-libs/nodejs
          - sys-apps/eza
          - dev-lang/php
          - dev-python/setuptools
          - sys-apps/ripgrep
          - kde-apps/kcachegrind
          - dev-util/github-cli
          - www-client/google-chrome
          - app-admin/terraform
          - dev-lang/spidermonkey
          - x11-misc/xvfb-run
          - media-video/ffmpeg
          - x11-apps/mesa-progs
          - app-shells/sheldon
          - dev-util/pkgdev
          - dev-util/pkgcheck
          - dev-dotnet/dotnet-sdk-bin
          - net-dns/bind-tools
          - net-misc/whois
          - dev-libs/json-glib
          - dev-dotnet/omnisharp-roslyn
          - app-misc/jq
          - dev-db/pgcli
          - dev-db/litecli
          - dev-db/mycli
          - dev-vcs/git-lfs
          - dev-java/openjdk-bin

    - name: Install node.js packages globally.
      community.general.npm:
        name: "{{ item }}"
        global: true
      loop:
        - wsl-open
        - yarn
