---
- hosts: localhost
  become: true
  gather_facts: false
  tasks:

    - copy:
        src: ./etc/portage/make.conf
        dest: /etc/portage/make.conf
        owner: root
        group: root
    - copy:
        src: ./etc/portage/package.accept_keywords/chromedriver-bin
        dest: /etc/portage/package.accept_keywords/chromedriver-bin
        owner: root
        group: root
    - copy:
        src: ./etc/portage/package.accept_keywords/emacs
        dest: /etc/portage/package.accept_keywords/emacs
        owner: root
        group: root
    - copy:
        src: ./etc/portage/package.accept_keywords/firebird
        dest: /etc/portage/package.accept_keywords/firebird
        owner: root
        group: root
    - copy:
        src: ./etc/portage/package.accept_keywords/github-cli
        dest: /etc/portage/package.accept_keywords/github-cli
        owner: root
        group: root
    - copy:
        src: ./etc/portage/package.accept_keywords/litecli
        dest: /etc/portage/package.accept_keywords/litecli
        owner: root
        group: root
    - copy:
        src: ./etc/portage/package.accept_keywords/mysql
        dest: /etc/portage/package.accept_keywords/mysql
        owner: root
        group: root
    - copy:
        src: ./etc/portage/package.accept_keywords/php
        dest: /etc/portage/package.accept_keywords/php
        owner: root
        group: root
    - copy:
        src: ./etc/portage/package.accept_keywords/terraform
        dest: /etc/portage/package.accept_keywords/terraform
        owner: root
        group: root
    - copy:
        src: ./etc/portage/package.mask/emacs
        dest: /etc/portage/package.mask/emacs
        owner: root
        group: root
    - copy:
        src: ./etc/portage/package.mask/mysql
        dest: /etc/portage/package.mask/mysql
        owner: root
        group: root
    - copy:
        src: ./etc/portage/package.unmask
        dest: /etc/portage/package.unmask
        owner: root
        group: root
    - copy:
        src: ./etc/portage/package.use/emacs
        dest: /etc/portage/package.use/emacs
        owner: root
        group: root
    - copy:
        src: ./etc/portage/package.use/git
        dest: /etc/portage/package.use/git
        owner: root
        group: root
    - copy:
        src: ./etc/portage/package.use/mysql
        dest: /etc/portage/package.use/mysql
        owner: root
        group: root
    - copy:
        src: ./etc/portage/package.use/nodejs
        dest: /etc/portage/package.use/nodejs
        owner: root
        group: root
    - copy:
        src: ./etc/portage/package.use/onedrive
        dest: /etc/portage/package.use/onedrive
        owner: root
        group: root
    - copy:
        src: ./etc/portage/package.use/php
        dest: /etc/portage/package.use/php
        owner: root
        group: root
    - copy:
        src: ./etc/portage/package.use/pinentry
        dest: /etc/portage/package.use/pinentry
        owner: root
        group: root
    - copy:
        src: ./etc/portage/package.use/systemd
        dest: /etc/portage/package.use/systemd
        owner: root
        group: root
    - copy:
        src: ./etc/portage/repos.conf/gentoo.conf
        dest: /etc/portage/repos.conf/gentoo.conf
        owner: root
        group: root
